# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.pcc.ript
canonical: http://profiles.ihe.net/PCC/RIPT
version: 0.1.0
name: IHE_PCC_RIPT
title: "IHE PCC - Routine Interfacility Patient Transport (RIPT)"
description: This Implementation Guide addresses patient transport between hospitals and Emergency Medical Service (EMS) systems. Defining the hospital patient discharge documentation provided to the EMS transport team that informs them of important patient care information. 
status: active
publisher:
  - name: IHE Patient Care Coordination
  - url: https://www.ihe.net/ihe_domains/patient_care_coordination/
  - email: pcc@ihe.net
contact:
  - name: IHE Patient Care Coordination
    telecom:
      - system: email
        value: pcc@ihe.net
license:  CC-BY-SA-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2021+
releaseLabel: ci-build


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
  index.md:
    title: RIPT Home
    generation: markdown
  volume-1.md:
    title: RIPT Volume 1
    generation: markdown
  PCC-1.md:
    title: 2:3.YY Transaction one [PCC-1]
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  issues.md:
    title: Open and Closed issues
    generation: markdown

menu:
  RIPT Home: index.html
  Volume 1:
    Refferal For Interfacility Patient Transport Profile: volume-1.html
  Volume 2:
    "Transaction one [PCC-1]": PCC-1.html
  Test Plan: testplan.html
  Artifacts: artifacts.html
